VIRTS1475: Multiple choice and fill in the blank
mitre/training pull request #100
Opened 2020-09-02 16:34 UTC by mchan143

2020-09-09 01:18 UTC, unkempthenry requested changes
Looks really good, see my comments for a couple tweaks to make.

2020-09-09 01:18 UTC, unkempthenry commented on app/c_navigator.py
> +    def __init__(self, number, name, challenge, answer, extra_info=None):
let's make extra_info default to an empty string instead of None: `extra_info=''`

2020-09-09 01:18 UTC, unkempthenry commented on app/c_multiplechoice.py
> +    def __init__(self, number, name, challenge, options, multi_select, answer, extra_info=None):
let's make extra_info default to an empty string instead of None: `extra_info=''` 

Also, change this on c_flag.Flag so they match. This way it can just be an optional argument for any question type.

2020-09-09 01:18 UTC, unkempthenry commented on hook.py
> +                    if hasattr(loaded_module, 'flag_type'):
can we get rid of this if-else block if we add `Flag` to the `question_types` dict? 

```
getattr(loaded_module, 'flag_type', 'standard_flag')
...

2020-09-09 01:18 UTC, unkempthenry commented on app/c_navigator.py
> +class Navigator(Flag, BaseObject):
Since, this class name is less obvious, add a short doc-string here explaining what this question type is (e.g. "Checks if a provided attack navigator layer files contains the required (Tactic, Technique) mappings" )

2020-09-09 01:18 UTC, unkempthenry commented on app/c_exam.py
> +class Exam(Certification, BaseObject):
Add a quick docstring here that covers how the Exam type is different from the standard Certification type (1 sentence fine--this just helps people orient themselves when they see the class for the first time).

2020-09-09 01:20 UTC, unkempthenry commented
Note: this PR adds the basic functionality, the following are enhancements we can add in the future: 

1. User answers are retained after submitting 
2. Hide big red X when flag has not been deleted (at least for the exam type) 
3. Support adding exam question types to non-Exam certifications
4. Support adding dynamic flag questions to Exam type certifications

2020-09-09 19:36 UTC, unkempthenry commented on hook.py
> +                    if hasattr(loaded_module, 'flag_type'):
this will be considered in a separate PR

2020-09-09 19:37 UTC, unkempthenry approved these changes

2020-09-12 20:46 UTC, unkempthenry commented
Example: 

<img width="1570" alt="Screen Shot 2020-09-12 at 4 34 47 PM" src="https://user-images.githubusercontent.com/31480194/93004671-1a266c00-f517-11ea-9968-3cc20c40b793.png">

Here are the files to create what's shown in the screenshot
[test_data.zip](https://github.com/mitre/training/files/5213214/test_data.zip)

2020-09-14 17:44 UTC, wbooth commented on app/c_fillinblank.py
> +                    completed_ts=self.completed_ts.strftime('%Y-%m-%d %H:%M:%S') if self.completed_ts else '')
move completed_ts  to function in flag
also should avoid acronyms where possible

2020-09-15 17:40 UTC, wbooth commented on hook.py
> +from importlib import import_module
importlib is standard lib and doesn't need to be moved

2020-09-16 14:08 UTC, merged