VIRTS1565 Training Flag Refactor
mitre/training pull request #107
Opened 2021-01-15 20:56 UTC by mchan143

Goals of PR (in no particular order?):
- Make it easier for CALDERA users to define flags
- Reduce code repetition in existing flags
- Abstract flag type (multiplechoice/fillintheblank/navigator) from loading flags into CALDERA instead of checking for `flag_type` attribute
- [Self registration of flag subclasses](https://python-3-patterns-idioms-test.readthedocs.io/en/latest/Metaprogramming.html#example-self-registration-of-subclasses)

To-do:
- [X] Test multiplechoice, fill in the blank, and navigator layer upload question types:  [test_data.zip](https://github.com/mitre/training/files/5822816/test_data.zip)
- [ ] Test user certificate
- [ ] Test blue certificate
- [ ] Test any remaining implemented flags not in a certificate (these are not currently assigned to any particular certificate, but were created and kept to maybe be included in a future certificate?)

Flags not in a certificate:
Developers
- flag_0
- flag_1
- flag_2
- flag_3
- flag_4
- flag_5
- flag_6
- flag_7

Manual
- blue_1a
- blue_1b
- blue_3a
- blue_3b
- blue_4a_nix
- blue_4a_win
- blue_4b_nix
- blue_4b_win
- blue_4c_nix
- blue_4c_win
- blue_5a_nix
- blue_5b_nix
- blue_5c_nix
- blue_5d_nix

2021-01-19 17:25 UTC, mchan143 commented
Some flags rely on the new `ran_ability_id` function to be added in https://github.com/mitre/caldera/pull/2008

2021-01-20 14:58 UTC, mchan143 commented
Wasn't able to get rid of `import_module` nor the `**attrs` with creating the flags since, if we were to instantiate the actual flag class, we'd need to definite `__init__` which means we wouldn't be able to avoid having the call to super().

2021-02-04 22:45 UTC, unkempthenry requested changes
This is starting to look really good.  Recommend changing 1 - 2 more things.

2021-02-04 22:45 UTC, unkempthenry commented on hook.py
> +                        filtered_registry = {k: v for k, v in Flag.registry.items() if v['module_name'] == module_name}
This is one part that's still awkward to me.  Maybe instead of a list of the modules, the Badges should be a list of class names.  Then we could load all flags, and then iterate over the lists of flags from each badge, pull it out of the registry, and construct it. 

This PR is already massive though due to refactoring every flag, and I think that change to badges is fine to happen in a follow up (think it would be just a few lines + changes the badge definitions)

2021-02-04 22:45 UTC, unkempthenry commented on hook.py
>                  for number, module in enumerate(data['flags']):
why do we need to use `flag_number` instead of the `number` we're getting from this for loop.  Can we get rid of the `flag_number` variable and use number instead?

2021-02-04 22:45 UTC, unkempthenry commented on hook.py
> +    attrs = {attr: getattr(cls, attr, None) for attr, val in vars(cls).items() if getattr(cls, attr, None) is not None
Can we get rid of this since we're saving these as class attributes now?  I don't think we should need to pass these values into the constructor anymore:

```python
class InsAttribs:
    def __init__(self, name):
        self.name = name

i = InsAttribs('flaggy')
print(i.name)
```
should give us "flaggy" 

```python
class ClassAttribs:
    name = "flaggy"
  
c = ClassAttribs()
print(c.name)
```
also gives us "flaggy", without having to discover the class attribute and inject it into `__init__`

2021-02-04 22:45 UTC, unkempthenry commented on hook.py
> +    attrs = {attr: getattr(cls, attr, None) for attr, val in vars(cls).items() if getattr(cls, attr, None) is not None
Ideally, we can replace this function with: 

`cls(number)`

(`number` is kind of annoying too, but we can wait til another PR to tackle it. )

2021-02-04 22:45 UTC, unkempthenry commented on hook.py
> +                        for cls, cls_attrs in filtered_registry.items():
recommend renaming `cls` to something else (`flag_class`).  `cls` is not really a language keyword, but there's heavy convention to use it in classmethods.  Renaming it might make things easier for a newcomer to read.

2021-02-05 15:20 UTC, bworrell commented on app/c_flag.py
> +class RegisterLeafClasses(type):
I read something a while back about metaclasses that I've tried to embrace since:

> Metaclasses are deeper magic than 99% of users should ever worry about. If you wonder whether you need them, you don’t (the people who actually need them know with certainty that they need them, and don’t need an explanation about why).  -- Tim Peters

I haven't looked at the uses of the registry in the other modules, but in the past when I've built a class/plugin/foobar registry I've typically done it using a class decorator (often a viable alternative to a metaclass) or just function calls.

Say you had a module called `flag_registry.py`

```python
# flag_registry.py

__flag_class_registry = [] # or a map like you had

def register_flag(flag_class)
    """Registers the given Flag class as a concrete Flag implementation."""
    __flag_class_registry.append(class)
    return flag class
```

Then whenever you wanted to register a concrete flag implementation you'd decorate that class

```python
# flag0.py
import flag_registry

class BaseFlag(object):
    # not registered because not a concrete Flag

@flag_registry.register_flag
class Flag(BaseFlag):
    name = "foo"
    description = "bar"
```

Or if the class decorators are too magical looking you can call a function after the class definition:

```python
# flag0.py
import flag_registry

class Flag(BaseFlag):
    name = "foo"
    description = "bar"


flag_registry.register_flag(Flag)
```

I'm still mulling over whether it's a worthwhile change, but I figured I'd share some thoughts on metaclass use and alternatives :)

2021-02-05 16:05 UTC, mchan143 commented on hook.py
>                  for number, module in enumerate(data['flags']):
Since `number` is the index of the flag within a specific badge and our certifications have multiple badges, the numbering should be increasing from the first flag to the last and not start over from 0 for each badge.

2021-02-05 17:23 UTC, bworrell commented on app/c_flag.py
> +               op.ran_ability_id('3b4640bc-eacb-407a-a997-105e39788781')
I often prefer boring looking code [to comprehensions with sub-comprehensions](https://google.github.io/styleguide/pyguide.html#274-decision) since it often reads easier to me and can make it easier to refactor or introduce new code.

A couple things I noticed:

* It seems like the inner `[f.trait for f in op.all_facts()]` comprehension is going to be evaluated once for each pass through the `['remote.port.unauthorized', 'host.pid.unauthorized']` trait list.
* If possible, use sets for membership checks rather than lists (O(1) vs. O(n)).
* The `op.ran_ability(...)` feels like it should be executed early if it is a fast method rather than looping.

This could be done a bunch of ways (e.g, use `set` operations) but here's an untested alternative that reads a bit more intuitively to me (IMO):

```python
if not op.ran_ability_id('3b4640bc-eacb-407a-a997-105e39788781'):
    return False

operation_traits = set(f.trait for f in op.all_facts())

if 'remote.port.unauthorized' not in operation_traits:
  return False
if 'host.pid.unauthorized' not in operation_traits:
  return False
return True
```

Some quesions/thoughts that probably don't need to be addressed in this PR:
* I've noticed ability ids sprinkled through other code in caldera so i'm not sure how ubiquitous they are, but to me they have a bit of a [magic number smell](https://refactoring.guru/replace-magic-number-with-symbolic-constant) and could benefit from constants defined elsewhere.
* Similar to the previous one, the traits themselves feel like they could benefit from a constants module to avoid spelling mistakes and allow for potentially easier refactoring.

2021-02-05 17:55 UTC, unkempthenry commented on app/c_flag.py
> +class RegisterLeafClasses(type):
Yeah, I generally agree about metaclasses.  I think this case is one of the reasonable uses for them though. 

The decorator could avoid a problem in the future if someone tried to subclass a "concrete" flag though so it might be worth it.  I like that the metaclass registry works completely behind the scenes though, but find myself going back and forth on which approach I think is "better". 

We might need to find someone with a stronger opinion -- or just let @mchan143 go the direction she thinks is better.

2021-02-05 19:26 UTC, mchan143 commented on hook.py
> +                        filtered_registry = {k: v for k, v in Flag.registry.items() if v['module_name'] == module_name}
How would you feel about the badges in a certification yml looking like this:

```
id: 9cd5f3a0-765d-45bc-85c2-bc76d4282599
name: User Certificate
description: "Basic user certificate."
badges:
  agents:
    flags:
      - flags.agents.flag_0.AgentsFlag0
      - flags.agents.flag_1.AgentsFlag1
...
```
where instead of `flags.agents.flag_0` it's `flags.agents.flag_0.AgentsFlag0`?

Loading the modules like this is already supported in the caught exception block, and you avoid looking through the registry for the subclasses that got registered. If we don't need to look through the registry anymore, then we won't need to have the metaclass/registry implementation either. 

The functionality lost would be the capability to define multiple flags in a single python file, of which there are no flag files currently doing yet anyways.

2021-02-05 19:48 UTC, bworrell commented on hook.py
> +                        filtered_registry = {k: v for k, v in Flag.registry.items() if v['module_name'] == module_name}
Agreed! The new class-based approach could possibly allow us to flatten out the package hierarchy and simplify loading a bit. Not needed for this PR but something to think about.

2021-02-05 19:53 UTC, bworrell commented on app/c_flag.py
> +                    resettable='True' if self.additional_fields and 'adversary_id' in self.additional_fields
The logic for `resettable` feels like it should be a property or method given how the others are being set.

2021-02-05 19:57 UTC, bworrell commented on app/c_flag.py
>          self.extra_info = extra_info
Are `name`, `challenge`, and `extra_info` needed as initialization parameters? It looks like most/all `Flag` classes have these defined as class-level attributes.

2021-02-05 19:58 UTC, mchan143 commented on app/c_flag.py
>          self.extra_info = extra_info
Moving these out as we speak actually :) Just about to push it up.

2021-02-05 20:06 UTC, mchan143 commented on hook.py
> +                        for cls, cls_attrs in filtered_registry.items():
Updated in https://github.com/mitre/training/pull/107/commits/ee7f8b8b40ab255cabfd45c74cc4c85e3fdd38c6

2021-02-05 20:06 UTC, mchan143 commented on hook.py
> +    attrs = {attr: getattr(cls, attr, None) for attr, val in vars(cls).items() if getattr(cls, attr, None) is not None
Updated in https://github.com/mitre/training/pull/107/commits/ee7f8b8b40ab255cabfd45c74cc4c85e3fdd38c6

2021-02-05 20:16 UTC, mchan143 commented on app/c_flag.py
> +               op.ran_ability_id('3b4640bc-eacb-407a-a997-105e39788781')
I think this was one of the blocks I had just pulled from the existing flags, happy to unpack it for clarity and readability

2021-02-05 20:24 UTC, bworrell commented on app/c_flag.py
> +class RegisterLeafClasses(type):
Because the flags are basically property bags w/ verification logic my gut says that the issue with extension isn't likely to be hit (there's likely not much of a reason to share data across flags) but I could be wrong. I'm fine with keeping it until there is an issue. But in general, in regards to metaclasses I'm gonna take the stance of "unless you can prove to me this is necessary or a significant improvement over alternatives, get 'em outta here" :)

2021-02-05 20:33 UTC, bworrell commented on app/c_flag.py
> +               op.ran_ability_id('3b4640bc-eacb-407a-a997-105e39788781')
Ah ok, that makes sense. Yeah if you could unpack it that'd be awesome!

2021-02-05 20:33 UTC, bworrell commented on app/c_flag.py
>          self.extra_info = extra_info
Nice!

2021-02-05 20:46 UTC, bworrell commented on hook.py
> +                        filtered_registry = {k: v for k, v in Flag.registry.items() if v['module_name'] == module_name}
Sorry, I think when I posted my reply I only saw the post from @unkempthenry. 

A fully-qualified import path seems reasonable to me. What I was thinking about potentially doing was putting all the flags for a particular badge/category in a single file and then the yaml would look like:

```yaml
id: foo
name: bar
description: baz
badges:
  agents:
    - AgentsFlag0
    - AgentsFlag1
  adversaries:
    - AdversaryFlag0
    - ...
```

So there'd be an `badges/agents.py` file with those classes in there. I'm normally advocating for splitting up large python modules so this feels a bit off and I may be forgetting something :) Anyway, the full import path seems fine to me.

2021-02-05 23:07 UTC, garunagiri requested changes
Many nested functions that use the 'op' variable receive it as an explicit parameter, but there are several that access the variable just through scoping. Not passing op as a parameter could cause some confusion when reading the code. Making all of these functions consistent such that op is passed explicitly would make this easier to understand. I've marked the locations I found this to occur.

2021-02-05 23:07 UTC, garunagiri commented on app/flags/autonomous/blue_2.py
> +            return op.ran_ability_id('5ec7ae3b-c909-41bb-9b6b-dadec409cd40')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/autonomous/blue_3.py
> +            return op.ran_ability_id('2ca64acd-dc12-4cc8-b78a-6a182508a50b')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_4a_nix.py
> +            return op.ran_ability_id('ba907d7a-b334-47e7-b652-4e481b5aa534')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_4a_win.py
> +            return op.ran_ability_id('a65a62e1-b8c0-4f88-b564-166e7499d560')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_4c_nix.py
> +            return op.ran_ability_id('32e563bb-ba06-4bcc-b817-fc2c434c0b66')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_4c_win.py
> +            return op.ran_ability_id('4744d99f-5fea-42a8-8ec4-c228db57caea')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_5a_nix.py
> +            return op.ran_ability_id('622e4bda-e5a8-42bb-93d9-a7b1eebc7e41')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_5a_win.py
> +            return op.ran_ability_id('83d7cf63-e10a-4615-a92e-dce257bf3b9d')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_5b_nix.py
> +            return op.ran_ability_id('df9d2b83-b40f-4167-af75-31ddde59af7e')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_5b_win.py
> +            return op.ran_ability_id('90a67a85-e81c-4525-8bae-12a2c5787d9a')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_5d_nix.py
> +            return op.ran_ability_id('e846973a-767b-4f9c-8b9e-5249cfcd7b97')
Place where op isn't passed

2021-02-05 23:07 UTC, garunagiri commented on app/flags/manual/blue_5d_win.py
> +            return op.ran_ability_id('e846973a-767b-4f9c-8b9e-5249cfcd7b97')
Place where op isn't passed

2021-02-08 15:52 UTC, garunagiri approved these changes

2021-02-08 16:14 UTC, unkempthenry commented on hook.py
> +                        filtered_registry = {k: v for k, v in Flag.registry.items() if v['module_name'] == module_name}
@bworrell 's example was how I was originally thinking -- however, doing an import path would probably obviate the need for the registry which may be nice.  If we do go the absolute import route, I'd recommend delimiting the class name, which would allow multiple flags in the same module: 

```yaml
badges:
  badge_name:
    - flags.agents.flags:AgentsFlag0
    - flags.agents.flags:AgentsFlag0
```

Note: not saying we should refactor the existing flags further to be in the same module -- but this would let us have that option.

2021-02-08 16:19 UTC, unkempthenry approved these changes
looking good to me (I'm happy with whichever direction for the the certification yaml goes). 

@bworrell is working on adding some new functionality to rey, so his approval is the most important before we merge.

2021-02-08 17:10 UTC, mchan143 commented on hook.py
> +                        filtered_registry = {k: v for k, v in Flag.registry.items() if v['module_name'] == module_name}
@bworrell incorporated in https://github.com/mitre/training/pull/107/commits/cea99cf144e1d1495b3a3584240b62cf0618f509

2021-02-08 19:01 UTC, bworrell requested changes
Overall looking really good! I like the class-based approach a lot and it seems to have allowed for some simplification of the loading logic 🎉  Just a small nit regarding the yaml format to address.

2021-02-08 19:01 UTC, bworrell commented on data/certifications/8da8f0b3-194a-4eed-95b0-43c1f1b64091.yml
> +    - flags.agents.blue_0:AgentsBlue0
Small nit, but can we the separator between the class and the partial module path a dot? Reprs for classes/modules usually depict a dotted notation.

ex:
```
<class 'plugins.training.app.flags.agents.blue_0.AgentsBlue0'>
```

2021-02-08 19:25 UTC, bworrell reviewed
One thing I noticed is that my caldera server failed to load with a data service error, which was attempting to restore some previous training module state:

```
Traceback (most recent call last):
  File "/Users/bworrell/code/caldera/server.py", line 106, in <module>
    run_tasks(services=app_svc.get_services())
  File "/Users/bworrell/code/caldera/server.py", line 45, in run_tasks
    loop.run_until_complete(data_svc.restore_state())
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bworrell/code/caldera/app/service/data_svc.py", line 60, in restore_state
    ram = pickle.loads(store)  # nosec
AttributeError: Can't get attribute 'verify' on <module 'plugins.training.app.flags.agents.blue_0' from '/Users/bworrell/code/caldera/plugins/training/app/flags/agents/blue_0.py'>
```

Is this expected?

2021-02-08 21:45 UTC, mchan143 commented
Per our discussion, restoring from an existing state is most likely the reason for the error since this PR makes changes to how flags are created and stored. The object store will therefore need to be dumped and the server started with `--fresh` in order to accomodate the changes introduced in this PR.

2021-02-08 21:47 UTC, bworrell approved these changes
LGTM!

2021-02-10 16:07 UTC, merged