Training UI update
mitre/training pull request #126
Opened 2021-05-25 14:58 UTC by iguannalin

## Description

UI revamp of training plugin, replacing JQuery with Alpine.js & native JS

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [n/a] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [n/a] I have made corresponding changes to the documentation
- [n/a] I have added tests that prove my fix is effective or that my feature works

2021-05-26 18:56 UTC, b17zr requested changes
This looks great!

One blocking change request: Is there a way to auto-update flag status that doesn't require closing and re-opening the plugin/badge? Tested by starting the server, opening the training plugin, opening the user certificate, then starting an agent. The flag isn't marked as complete until either closing and re-opening the plugin, or switching the badge to blue and back.

2021-05-27 13:43 UTC, argaudreau requested changes
I also think this looks great! Very slick UI.

In addition to Mitch's comment, do you think we should grey out the different categories (adversaries, operations, advanced, etc.) till the previous tab was completed? Otherwise it may seem like users can jump to any section at any time and complete a flag, but they have to complete it one by one from the start.

2021-05-27 13:43 UTC, argaudreau commented on templates/training.html
> +                    <span role="button" class="plugin-x-button hover:bg-caldera-primary rounded pl-1" onclick="removeSection('training')">
This is very nit-picky, but could we move the X button to the top left of the section instead of the top right? Currently the other windows have it on the left so I kept missing it when trying to close the window.

We can talk about the placement when we revamp the UI, because I'm used to it being on the top right too but I think it's better to be consistent for now.

2021-05-28 03:54 UTC, iguannalin commented on templates/training.html
> +                    <span role="button" class="plugin-x-button hover:bg-caldera-primary rounded pl-1" onclick="removeSection('training')">
Yeah, that's something I was conflicted about as well. On the one hand, I want to keep it consistent, but on the other, it looks slightly off when I keep it on the left with the current UI:

<img width="478" alt="Screen Shot 2021-05-27 at 11 52 30 PM" src="https://user-images.githubusercontent.com/32778440/119927130-8c5ba700-bf14-11eb-8c5f-bef918405617.png">

2021-05-28 03:57 UTC, iguannalin commented on templates/training.html
> +                    <span role="button" class="plugin-x-button hover:bg-caldera-primary rounded pl-1" onclick="removeSection('training')">
And to your comment above about graying out categories, we had a discussion before where we decided to let the users decide if they want to go ahead and complete a flag not in the order laid out on screen--just based on some feedback where some users felt frustrated they couldn't skip around as some of the flags could have been done along with other ones. As a result we decided to just have it all displayed from the beginning so users can see everything they need to do to complete the training.

2021-05-28 03:59 UTC, iguannalin commented
> This looks great!
> 
> One blocking change request: Is there a way to auto-update flag status that doesn't require closing and re-opening the plugin/badge? Tested by starting the server, opening the training plugin, opening the user certificate, then starting an agent. The flag isn't marked as complete until either closing and re-opening the plugin, or switching the badge to blue and back.

That's a good catch, thanks! I put in a refresh for every 15 seconds now like how it was done before, to fetch any updates for the flags from the endpoint. I checked this with the network tab and it seems to be working fine.

2021-05-28 16:07 UTC, b17zr requested changes
Would it be possible to only update the flag statuses during the refresh, instead of refreshing all the flag?

Example:

1. Open Training plugin, User certificate
2. Click Advanced badge, 3 flags shows
3. When flags are refreshed, all flags are shown

2021-06-01 15:45 UTC, argaudreau approved these changes

2021-06-02 16:51 UTC, argaudreau approved these changes

2021-06-02 17:01 UTC, merged